apiVersion: v1

kind: Pod

metadata:
    name: myapp-pod
    labels: 
        app: myapp
        costcenter: eu
        location: eu
        type: example        

spec:
    containers:
        - name: nginx
          image: nginx
    affinity:
        nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                    - matchExpressions:
                        - key: size
                          operator: In
                          values:
                            - Large