apiVersion: v1

kind: Pod

metadata:
    name: myapp-pod
    labels: 
        app: myapp
        costcenter: eu
        location: eu
        type: example        

spec:
    containers:
        - name: nginx-container
          image: nginx
    nodeName: k8sn
