apiVersion: apps/v1

kind: DaemonSet

metadata:
    name: monitoring-daemonset

spec:
    selector:
        matchLabels:
            app: monitoring
    template:
        metadata:
            labels: 
                app: monitoring        
        spec:
            containers:
                - name: nginx
                  image: nginx            
            
